const fs = require('fs');
const path = require('path');

const dbFiles = [
  '01-schema-seed.sql',
  '02-mock-data.sql',
  '03-rechnungen.sql',
  '04-peak-season-mock-data.sql'
];

const basePath = 'c:/Users/Lukas/Projekte/WAB-hotel-Manager/db/init';

for (const file of dbFiles) {
  const fullPath = path.join(basePath, file);
  if (!fs.existsSync(fullPath)) continue;
  let content = fs.readFileSync(fullPath, 'utf8');

  // Replace primary key definitions
  content = content.replace(/CREATE TABLE IF NOT EXISTS ([a-zA-Z_]+)\s*\(\s*id int (generated|GENERATED)/ig, (match, tableName, gen) => {
    return `CREATE TABLE IF NOT EXISTS ${tableName}\n(\n  ${tableName.toLowerCase()}_id int ${gen}`;
  });

  content = content.replace(/CREATE TABLE IF NOT EXISTS ([a-zA-Z_]+) \(id int (generated|GENERATED)/ig, (match, tableName, gen) => {
    return `CREATE TABLE IF NOT EXISTS ${tableName} (${tableName.toLowerCase()}_id int ${gen}`;
  });

  // Specifically for Mitreisender one-liner in 01-schema-seed.sql
  // CREATE TABLE IF NOT EXISTS Mitreisender (id int generated by default as identity primary key, ...);

  // Replace FOREIGN KEY references
  // FOREIGN KEY (kategorie_id) REFERENCES Kategorie(id)
  // REFERENCES Kategorie(id)
  const refTables = ['Kategorie', 'zimmer', 'Status', 'Mitarbeiter', 'Wird_Betreut_Von', 'Gast', 'Gast_Aenderung', 'Reservierung', 'Mitreisender', 'Reservierung_Aenderung', 'Zusatzleistung', 'Rechnung'];
  for (const table of refTables) {
    const tableId = table.toLowerCase() + '_id';
    const regex = new RegExp(`REFERENCES\\s+${table}\\s*\\(\\s*id\\s*\\)`, 'ig');
    content = content.replace(regex, `REFERENCES ${table}(${tableId})`);
  }

  content = content.replace(/REFERENCES\\s+Zimmer\\s*\\(id\\)/ig, 'REFERENCES Zimmer(zimmer_id)');

  fs.writeFileSync(fullPath, content);
  console.log(`Updated ${file}`);
}
