CREATE TABLE IF NOT EXISTS Kategorie
(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  preis decimal(10,2),
  betten_anzahl int,
  beschreibung text
);

CREATE TABLE IF NOT EXISTS zimmer
(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nummer int,
  aktiv boolean,
  kategorie_id int,
  FOREIGN KEY (kategorie_id) REFERENCES Kategorie(id)
);

CREATE TABLE IF NOT EXISTS Status
(
  id int generated by default as identity primary key,
  name text
);

CREATE TABLE IF NOT EXISTS Mitarbeiter
(
  id int generated by default as identity primary key,
  vorname text,
  nachname text,
  geburtsdatum date,
  telefonnummer text,
  email text,
  verantwortlichkeit_id int
);

CREATE TABLE IF NOT EXISTS Wird_Betreut_Von
(
  id int generated by default as identity primary key,
  mitarbeiter_id int,
  status_id int,
  foreign key (mitarbeiter_id) references Mitarbeiter(id),
  foreign key (status_id) references Status(id)
);

CREATE TABLE IF NOT EXISTS Gast
(
  id int generated by default as identity primary key,
  vorname text,
  nachname text,
  geburtsdatum date,
  telefonnummer text,
  email text,
  stadt text,
  land text,
  postleitzahl text,
  strasse text,
  hausnummer text
);

CREATE TABLE IF NOT EXISTS Gast_Aenderung
(
  id int generated by default as identity primary key,
  alter_wert text,
  neuer_wert text,
  feldname text,
  erstellt TIMESTAMPTZ NOT NULL DEFAULT now(),
  gast_id int,
  foreign key (gast_id) references Gast(id)
);

CREATE TABLE IF NOT EXISTS Reservierung
(
  id int generated by default as identity primary key,
  start date,
  ende date,
  erstellt TIMESTAMPTZ NOT NULL DEFAULT now(),
  gast_id int,
  status_id int,
  zimmer_id int,
  fruehstueck boolean default false,
  parkplatz boolean default false,
  bemerkung text,
  foreign key (gast_id) references Gast(id),
  foreign key (status_id) references Status(id),
  foreign key (zimmer_id) references Zimmer(id)
);

CREATE TABLE IF NOT EXISTS Mitreisender (id int generated by default as identity primary key, reservierung_id int references Reservierung(id) on delete cascade, vorname text, nachname text, geburtsdatum date);

CREATE TABLE IF NOT EXISTS Reservierung_Aenderung
(
  id int generated by default as identity primary key,
  alter_wert text,
  neuer_wert text,
  feldname text,
  erstellt TIMESTAMPTZ NOT NULL DEFAULT now(),
  reservierung_id int,
  foreign key (reservierung_id) references Reservierung(id)
);

INSERT INTO Kategorie (name, preis, betten_anzahl, beschreibung) VALUES
('Einzelzimmer Standard', 85.00, 1, 'Gemütliches Einzelzimmer mit Grundausstattung'),
('Doppelzimmer Komfort', 120.00, 2, 'Geräumiges Doppelzimmer mit moderner Ausstattung und Balkon'),
('Suite Luxus', 250.00, 2, 'Exklusive Suite mit separatem Wohnbereich und Panoramablick');

INSERT INTO zimmer (nummer, aktiv, kategorie_id) VALUES
(101, true, 1),
(102, true, 1),
(103, true, 1),
(201, true, 2),
(202, true, 2),
(301, true, 3);

INSERT INTO Status (name) VALUES
('Anfrage'),
('Bestätigt'),
('Storniert'),
('Check-in erfolgt'),
('Abgereist');

INSERT INTO Gast (vorname, nachname, email, telefonnummer, strasse, hausnummer, postleitzahl, stadt, land) VALUES
('Max', 'Mustermann', 'max.mustermann@example.com', '0123456789', 'Musterstraße', '1', '12345', 'Musterstadt', 'Deutschland'),
('Erika', 'Mustermann', 'erika.mustermann@example.com', '0987654321', 'Musterstraße', '1', '12345', 'Musterstadt', 'Deutschland');

INSERT INTO Reservierung (start, ende, gast_id, status_id, zimmer_id) VALUES
('2026-03-27', '2026-03-31', 1, 1, 1),
('2026-04-05', '2026-04-12', 2, 2, 4);

INSERT INTO Mitarbeiter (vorname, nachname, email, telefonnummer) VALUES
('Peter', 'Müller', 'peter.mueller@hotel.com', '0111222333'),
('Sarah', 'Schmidt', 'sarah.schmidt@hotel.com', '0444555666');
