CREATE TABLE IF NOT EXISTS Zusatzleistung
(
  zusatzleistung_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservierung_id int,
  name text,
  preis decimal(10,2),
  anzahl int default 1,
  FOREIGN KEY (reservierung_id) REFERENCES Reservierung(reservierung_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Rechnung
(
  rechnung_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservierung_id int UNIQUE,
  rechnungsnummer text,
  datum TIMESTAMPTZ NOT NULL DEFAULT now(),
  gesamtbetrag decimal(10,2),
  bezahlt boolean default false,
  datum_bezahlt TIMESTAMPTZ,
  FOREIGN KEY (reservierung_id) REFERENCES Reservierung(reservierung_id) ON DELETE CASCADE
);
