spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:wab}
spring.datasource.username=${PGUSER:wab}
spring.datasource.password=${PGPASSWORD:wab}
spring.datasource.driver-class-name=org.postgresql.Driver

# Server Port
server.port=${PORT:8080}

# Show SQL for debugging (optional)
spring.datasource.show-sql=true
